CREATE TABLE PRODUCT
(
	ID INT(11) NOT NULL,
	PRODUCTNAME VARCHAR(1000),
	CATEGORY VARCHAR(1000),
	PRICE INT(11),
	idINFO INT(11),
	idIMAGE INT(11),
	CONSTRAINT PK_PRODUCT PRIMARY KEY(ID)
)

CREATE TABLE ACCOUNT
(
	ID INT(11) NOT NULL,
	DISPLAYNAME NVARCHAR(50),
	EMAIL VARCHAR(50),
	PASSWORD VARCHAR(20)
	CONSTRAINT PK_ACCOUNT PRIMARY KEY(ID)
)

CREATE TABLE INFORMATION
(
	ID_LAP INT(11) NOT NULL,
	CHIP VARCHAR(1000),
	RAM VARCHAR(255),
	ROM VARCHAR(255),
	CARDSCREEN VARCHAR(255),
	SCREEN VARCHAR(255),
	HDH VARCHAR(255),
	WEIGHT VARCHAR(255)
	CONSTRAINT PK_INFO PRIMARY KEY(ID_LAP)
)

CREATE TABLE IMAGELAP
(
	ID_IMAGE INT(11) NOT NULL,
	IMG1 VARCHAR(255),
	IMG2 VARCHAR(255),
	IMG3 VARCHAR(255)
	CONSTRAINT PK_IMG PRIMARY KEY(ID_IMAGE)
)

ALTER TABLE dbo.PRODUCT ADD CONSTRAINT FK_PRODUCT_IMG FOREIGN KEY(idIMAGE) REFERENCES dbo.IMAGELAP
ALTER TABLE dbo.PRODUCT ADD CONSTRAINT FK_PRODUCT_INFO FOREIGN KEY(idINFO) REFERENCES dbo.INFORMATION

