CREATE TABLE PRODUCT
(
	ID INT NOT NULL,
	PRODUCTNAME VARCHAR(60),
	CATEGORY VARCHAR(20),
	PRICE INT,
	idINFO INT,
	idIMAGE INT,
	CONSTRAINT PK_PRODUCT PRIMARY KEY(ID)
)

CREATE TABLE ACCOUNT
(
	ID INT NOT NULL,
	DISPLAYNAME NVARCHAR(50),
	EMAIL VARCHAR(50),
	PASSWORD VARCHAR(50)
	CONSTRAINT PK_ACCOUNT PRIMARY KEY(ID)
)

CREATE TABLE INFORMATION
(
	ID_LAP INT NOT NULL,
	CHIP NVARCHAR(50),
	RAM VARCHAR(30),
	ROM NVARCHAR(50),
	CARDSCREEN NVARCHAR(50),
	SCREEN NVARCHAR(50),
	HDH NVARCHAR(20),
	WEIGHT NVARCHAR(30)
	CONSTRAINT PK_INFO PRIMARY KEY(ID_LAP)
)

CREATE TABLE IMAGELAP
(
	ID_IMAGE INT NOT NULL,
	IMG1 VARCHAR(100),
	IMG2 VARCHAR(100),
	IMG3 VARCHAR(100)
	CONSTRAINT PK_IMG PRIMARY KEY(ID_IMAGE)
)

ALTER TABLE dbo.PRODUCT ADD CONSTRAINT FK_PRODUCT_IMG FOREIGN KEY(idIMAGE) REFERENCES dbo.IMAGELAP
ALTER TABLE dbo.PRODUCT ADD CONSTRAINT FK_PRODUCT_INFO FOREIGN KEY(idINFO) REFERENCES dbo.INFORMATION

